export const countryCodeMap: { [key: string]: string } = {
  "United States": "US",
  Turkey: "TR",
  Canada: "CA",
  Germany: "DE",
  "United Kingdom": "GB",
  Australia: "AU",
  Austria: "AT",
  Belgium: "BE",
  Brazil: "BR",
  France: "FR",
  Italy: "IT",
  Spain: "ES",
  Mexico: "MX",
  Japan: "JP",
  "South Korea": "KR",
  Netherlands: "NL",
  Sweden: "SE",
  Switzerland: "CH",
  Denmark: "DK",
  Norway: "NO",
  Finland: "FI",
  Portugal: "PT",
  Greece: "GR",
  Poland: "PL",
  Russia: "RU",
  China: "CN",
  India: "IN",
  "South Africa": "ZA",
  Argentina: "AR",
  Chile: "CL",
  Colombia: "CO",
  Peru: "PE",
  "New Zealand": "NZ",
  Singapore: "SG",
  Malaysia: "MY",
  Thailand: "TH",
  Vietnam: "VN",
  Israel: "IL",
  "Saudi Arabia": "SA",
  "United Arab Emirates": "AE",
  Egypt: "EG",
  Jordan: "JO",
  Lebanon: "LB",
  Kuwait: "KW",
  Qatar: "QA",
  Bahrain: "BH",
  Oman: "OM",
  Iraq: "IQ",
  Pakistan: "PK",
  Bangladesh: "BD",
  "Sri Lanka": "LK",
  Nepal: "NP",
  Kazakhstan: "KZ",
  Uzbekistan: "UZ",
  Kyrgyzstan: "KG",
  Turkmenistan: "TM",
  Tajikistan: "TJ",
  Armenia: "AM",
  Georgia: "GE",
  Moldova: "MD",
  Belarus: "BY",
  Ukraine: "UA",
  Lithuania: "LT",
  Latvia: "LV",
  Estonia: "EE",
  Cyprus: "CY",
  Malta: "MT",
  Luxembourg: "LU",
  Monaco: "MC",
  Andorra: "AD",
  "San Marino": "SM",
  "Vatican City": "VA",
  Liechtenstein: "LI",
  "Isle of Man": "IM",
  Jersey: "JE",
  Guernsey: "GG",
  "Falkland Islands": "FK",
  Bermuda: "BM",
  "Cayman Islands": "KY",
  "British Virgin Islands": "VG",
  Anguilla: "AI",
  Montserrat: "MS",
  "Saint Helena": "SH",
  "Ascension Island": "AC",
  "Pitcairn Islands": "PN",
  Tokelau: "TK",
  Niue: "NU",
  "Cook Islands": "CK",
  "American Samoa": "AS",
  Samoa: "WS",
  Tonga: "TO",
  Nauru: "NR",
  Palau: "PW",
  "Marshall Islands": "MH",
  Micronesia: "FM",
  Guam: "GU",
  "Northern Mariana Islands": "MP",
  "Federated States of Micronesia": "FM",
  Vanuatu: "VU",
  "Solomon Islands": "SB",
  Kiribati: "KI",
  Tuvalu: "TV",
  Fiji: "FJ",
  "Papua New Guinea": "PG",
  "New Caledonia": "NC",
  "French Polynesia": "PF",
  "Wallis and Futuna": "WF",
  "French Southern and Antarctic Lands": "TF",
  "Saint Pierre and Miquelon": "PM",
  Greenland: "GL",
  "Faroe Islands": "FO",
  "Svalbard and Jan Mayen": "SJ",
  "Arctic Ocean": "AO",
};
